### ISSUE TITLE
Could you add sdkInt to get the Android API number?

### ISSUE THREAD

**Issue by JmyW** [Kent1011/client_information#11]
Not an issue but function request.

Thanks for offer this package. Through your package, I can read OS version but I cannot find a way to get the Android API number. For example, got OS version 7.0. But I hope to further get the API version 24 as integer number for comparison.

**Comment by Kent1011** [comment]
You can refer to osVersionCode in the latest version (2.1.1). In Android, it represents the Android API level.

**Comment by JmyW** [comment]
Thanks a lot for teaching. I didn't find the osVersionCode function. YES! it WORKS!
