### ISSUE TITLE
hi, thanks for the package, one question

### ISSUE THREAD

**Issue by jinfagang** [Kent1011/client_information#3]
Only one question:

Will the deviceId change after time, or, will it change when I reinstalled the app?

device_info and device_info_plus does.

**Comment by Kent1011** [comment]
In iOS, yes, it will changed.

client_information use `UIDevice.current.identifierForVendor` as iPhone's device id which can only make sure it's a unique string.

If you need to identify the same device, you can find more information from Apple's document: [DeviceCheck](https://developer.apple.com/documentation/devicecheck)

**Comment by jinfagang** [comment]
@Kent1011 How about Android?

**Comment by yingwei1025** [comment]
@jinfagang, deviceId in Android wont changes after reinstall app or restart phone unless manually changes it
